/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.hdfc.gradle;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Product product = new Product("pen", "blue", 10.00);
        System.out.println(product);
    }
}
